### ISSUE TITLE
[Bug]: Installation ERROR

### ISSUE THREAD

**Issue by hiwanz** [Comfy-Org/desktop#380] opened 2024-11-27 07:53 UTC
### App Version

ComfyUI 0.3.18-arm64

### Expected Behavior

Finish installation properly

### Actual Behavior

Unable to start ComfyUI Desktop v0.3.18

### Steps to Reproduce

Open app select comfyui path,starting installation,after downloading some resources,it shows "Unable to start ComfyUI Desktop v0.3.18"

### Debug Logs

```powershell
[2024-11-27 15:40:52.501] [info]    [31mx[0m Failed to extract archive:
  [31m|[0m cpython-3.12.4%2B20240726-aarch64-apple-darwin-install_only_stripped.tar.gz
[31m  |-> [0mfailed to unpack
[31m  |   [0m`/Users/hiwanz/ComfyUI/uv-cache/.cache/.tmpe0HC0M/python/lib/itcl4.2.2/libitcl4.2.2.a`

[2024-11-27 15:40:52.501] [info]  [31m  |-> [0mfailed to unpack `python/lib/itcl4.2.2/libitcl4.2.2.a` into
[31m  |   [0m`/Users/hiwanz/ComfyUI/uv-cache/.cache/.tmpe0HC0M/python/lib/itcl4.2.2/libitcl4.2.2.a`
[31m  |-> [0merror decoding response body
[31m  |-> [0mrequest or response body error
[31m  `-> [0moperation timed out

[2024-11-27 15:40:52.505] [info]  --end-1732693146286:1

[2024-11-27 15:40:52.505] [error] Error creating virtual environment: Error: Failed to create virtual environment: exit code 1
[2024-11-27 15:49:36.728] [info]  @todesktop/runtime: Checking for update
[2024-11-27 15:49:36.729] [info]  @todesktop/runtime: AutoUpdater: checking-for-update
[2024-11-27 15:49:38.057] [info]  @todesktop/runtime: Update for version 0.3.18 is not available (latest version: 0.3.18, downgrade is allowed).
[2024-11-27 15:49:38.058] [info]  @todesktop/runtime: AutoUpdater: update-not-available {
  version: '0.3.18',
  files: [
    {
      url: 'ComfyUI 0.3.18 - Build 241126kqn6q5ij3-arm64-mac.zip',
      sha512: 'AMdQBbn4ExbJInIcnOf2IVQdQ/osjSgWqdSkKkpaRhHHQKKZUouzhQTvvWZB8hC8Gx+msggNmenpQgT4DstQMA==',
      size: 137366227
    },
    {
      url: 'ComfyUI 0.3.18 - Build 241126kqn6q5ij3-arm64.dmg',
      sha512: 'FsfrDLm9bqQfnVtgkLEQ8xFrpQDL2GiP9dYrD9FXdni1zw6FzR0bnVlAOZRoQkpdj1MW/Zvm+68VL/ACrwf/wg==',
      size: 145078302
    }
  ],
  path: 'ComfyUI 0.3.18 - Build 241126kqn6q5ij3-arm64-mac.zip',
  sha512: 'AMdQBbn4ExbJInIcnOf2IVQdQ/osjSgWqdSkKkpaRhHHQKKZUouzhQTvvWZB8hC8Gx+msggNmenpQgT4DstQMA==',
  releaseDate: '2024-11-26T23:14:16.186Z'
}
```

### Browser Logs

none

### Setting JSON

none

### What browsers do you use to access the UI ?

Google Chrome

**Comment by robinjhuang** [comment] 2024-11-27 19:48
Looks like this is caused by anti-virus or some system level interruptions. 
https://github.com/astral-sh/uv/issues/6331

We can upgrade the uv version which automatically handle retries. Probably makes sense to display a way to retry from the UI as well.

**Comment by robinjhuang** [comment] 2024-12-07 00:24
Should be resolved in the latest version.

**Closed by robinjhuang** 2024-12-07 00:24 UTC
